### ISSUE TITLE
Maybe add this repo to the #prior-art- section?

### ISSUE THREAD

**Issue by megatux** [phlex-ruby/phlex#539]
Hi! awesome project, congrats!.
maybe adding this lib. as prior art? WDYT? or that list contains only _your_ experience with other libs?
- https://github.com/inesita-rb/inesita
  - https://inesita.fazibear.me

**Comment by joeldrapper** [comment]
Thanks @megatux. I’ve been trying to list all the projects exploring using Ruby for HTML generation, so this is perfect. Could you open a PR?
