### ISSUE TITLE
Events blocked in html makes it hard to write javascript

### ISSUE THREAD

**Issue by LukeClancy** [phlex-ruby/phlex#585]
I cant use javascript because onsubmit and other events seem to be blocked. How do I unblock all of these? I understand the filtering of something like this:

```ruby
p {
    %Q{<form onsubmit="console.log('this should not work') ">
        <button type="submit"> click me </button>
    </form>}
}
```

but if the user is writing phlex code such as below which also breaks, then the server has already been hacked (since you are writing ruby, and I think it is unlikely to intentionally put user input in the onsubmit event).
```ruby
form(url: "/test", onsubmit: 'console.log("this should work but does not")')
```

Also, depending on the libraries that are being used, at the point where the user is putting in unconstrained html, there are a thousand ways to do cross site scripting. For example, if you are blocking onsubmit, why are you not blocking stimulusjs's "data-action"? One could use that to destroy accounts, post data, and multiple other things.

This just doesn't seem like the place to put constraints IMO. Is there a way to turn it off? Either a configuration option or using html_safe like below would work.

```ruby
form(url: "/test", "onsubmit".html_safe => 'console.log("this should work but does not")')
```

Thank you for your time, I love your gem. It has solved many issues I had with erb and haml.

**Comment by stephannv** [comment]
You can monkey patch on an initializer:
```ruby
class Phlex::HTML
  EVENT_ATTRIBUTES = {}.freeze
end

# You will receive these warnings
# warning: already initialized constant Phlex::HTML::EVENT_ATTRIBUTES
# phlex-1.8.1/lib/phlex/html.rb:7: warning: previous definition of EVENT_ATTRIBUTES was here
```
