### ISSUE TITLE
'Clean' class attributes before generate HTML

### ISSUE THREAD

**Issue by owpac** [phlex-ruby/phlex#598]
Hello there!

I was wondering if it was possible to inline class attributes when generating the HTML.

For instance, this code:
```ruby
def template
  div(
    class: "
      flex
      items-center
      py-5
      px-5
    "
  ) do
    h1 { "coucou" }
  end
end
```

Generate this:
```html
<div class="
        flex
        items-center
        py-5
        px-5
      "><h1>coucou</h1></div>
```

Instead of this:
```html
<div class="flex items-center py-5 px-5"><h1>coucou</h1></div>
```

With the growing use of Tailwind, I think it could be a nice idea to distinguish how people format their Rails code and how the output will render.  What do you think?

If it is something that you agree with, I think I might be able to propose a PR by adding some logic [here](https://github.com/phlex-ruby/phlex/blob/5a4002f906dbf20e09fd087f51a5841e85187064/lib/phlex/elements.rb#L44).

Thank you for your work!

**Comment by joeldrapper** [comment]
Hey @owpac, thanks for the suggestion.

I think we've had something like this before and removed it for performance. I know it's not much and can usually be cached, but I’m a little obsessive about these things.

Most of the time, you don't need to normalise the spacing. And browsers do just fine with weird token spacing.

I think I could be convinced to add this as long as it didn't impact performance too much, but another option might just be to use Arrays, which are already supported and will produce nicely spaced token lists.

Here's how you could re-write the above example using an array.

```ruby
div(
  class: %w[
    flex
    items-center
    py-5
    px-5
  ]
)
```

**Comment by owpac** [comment]
Hello @joeldrapper, thanks a lot for your reply!

I didn't know it would consume that much performance, that's why I suggested it.

Your recommendation is doing the job, thanks a lot! 🙇 

Have a nice day!
