### ISSUE TITLE
rendering a view_component inside a phlex view doesn't work correctly

### ISSUE THREAD

**Issue by denis-mueller** [phlex-ruby/phlex#599]
I have a simple controller

```
# app/controllers/employee_zone/employees_controller.rb
module EmployeeZone
  class EmployeesController < EmployeeZone::EmployeeZoneController
    def new
     
    end
  end
end
```

and a corresponding view that just renders a simple view_component (https://github.com/viewcomponent/view_component)

```
# app/views/employee_zone/employees/new.html.erb
<%= render Element::Modal::Component.new do %>
  <h1>Hello from ERB</h1>
<% end %>
```

```
# app/components/element/modal/component.rb
module Element
  module Modal
    class Component < ApplicationViewComponent
      def call
        content_tag(:div, content, class: 'bg-white')
      end
    end
  end
end
```

this produces the following (expected) output when opening the page in the browser
```
<div class="bg-white">
  <h1>Hello from ERB</h1>
</div>
```

now if I try to replace my erb view with a equivalent phlex view
```
# app/views/employee_zone/employees/new_view.rb
module EmployeeZone
  module Employees
    class NewView < ApplicationView
      def template
        render Element::Modal::Component.new do
          h1 { 'Hello from Phlex' }
        end
      end
    end
  end
end
```

and use the phlex view in the controller

```
# app/controllers/employee_zone/employees_controller.rb
module EmployeeZone
  class EmployeesController < EmployeeZone::EmployeeZoneController
    def new
      render EmployeeZone::Employees::NewView.new
    end
  end
end
```

and inspect it in the browser, I see that the h1 tag renders outside of the div instead of inside of it:
```
 <h1>Hello from Phlex</h1><div class="bg-white"></div>
```

the expected behaviour would be that both the erb and the phlex view produce the same html output in the browser

**Comment by joeldrapper** [comment]
That is a very strange bug. When you call `render` in Phlex, it should hit this branch, which captures the phlex contents as a string via the call to `capture`, and then passes that string to the view component as if it had been from ActionView.

https://github.com/phlex-ruby/phlex-rails/blob/0055c2a7675e772350e57b7f05b6ceb5eeeb17c2/lib/phlex/rails/sgml/overrides.rb#L26

What do you receive as `content` in the `call` method on the view component? Are you able to `binding.irb` in there and inspect that?

**Comment by Spone** [comment]
Hi @denis-mueller! Have you tried enabling the [capture compatibility patch](https://viewcomponent.org/known_issues.html#issues-resolved-by-the-optional-capture-compatibility-patch) in ViewComponent?

**Comment by joeldrapper** [comment]
@spone that shouldn’t make a difference here, if I understand this correctly. Phelx’ `capture` method and internal buffer are entirely distinct from ActionView’s output buffer. Phlex sends this:

```ruby
@view_context.render(view_component_object) { "A string from Phlex" }
```

So the `view_component_object` should receive (via ActionView), something like this:

```ruby
render_in(view_context) { "A string from Phlex" }
```

**Comment by denis-mueller** [comment]
Thank you for the reply @joeldrapper 

Interestingly, when I use the phlex view, the `content` in the `call` method of the view component is nil.
When use ERB the `content` is an `ActiveSupport::SafeBuffer` (when i use `.inspect` I get `"\n  <h1>Hello from ERB</h1>\n"`)

**Comment by denis-mueller** [comment]
@Spone Thx for the suggestion!

I added
```
config.view_component.capture_compatibility_patch_enabled = true
```

to my `application.rb` but it didn't solve the problem

**Comment by joeldrapper** [comment]
Thanks @denis-mueller, I’ll try to reproduce this locally and figure out why that content is `nil`. It’s like it hasn’t done the `capture` at all because the content is being output early and then not being passed to the view component. 🤔

**Comment by joeldrapper** [comment]
@denis-mueller I did some testing and the good news is this is already fixed; I just haven't released that patch yet. I’m going to cut a release in the next few days. Until then, you should be able to get the fix by using edge versions directly from GitHub.

```ruby
gem "phlex", git: "https://github.com/phlex-ruby/phlex.git"
gem "phlex-rails", git: "https://github.com/phlex-ruby/phlex-rails.git"
```

**Comment by denis-mueller** [comment]
cool, thank you for your work joel! @joeldrapper
