### ISSUE TITLE
upgraded to ruby 3.2.2 have me see: ActionView::Template::Error (undefined method `<<' for nil:NilClass):

### ISSUE THREAD

**Issue by wdiechmann** [phlex-ruby/phlex#612]
I just barely escaped a giant blunder - not keeping my toolbelt in pristine condition 😮 
(suffice to say I (ultimately) realized that `homebrew upgrade ruby-build && asdf plugin update --all` had my back) 

That was my understanding - until I started seeing the title text in my logs 😮‍💨 

Upgraded from Ruby 3.1.2-something

```
√ src % gem -v
3.4.10
√ src % ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
√ src % 
```

My Gemfile.lock mentions

```
 phlex (1.9.0)
      concurrent-ruby (~> 1.2)
      erb (>= 4)
      zeitwerk (~> 2.6)
    phlex-rails (0.7.1)
      phlex (~> 1.4)
      rails (>= 6.1, < 8)
      zeitwerk (~> 2.6)

```

Everything was dandy until I added `gem 'commonmarker'` to my Gemfile - and pulled something 15G whilst trying to have my deploys succeed - and when they did, only to see this in my log:

```
Completed 500 Internal Server Error in 118ms (ActiveRecord: 41.0ms | Allocations: 60385)

ActionView::Template::Error (undefined method `text' for #<Views::Components::Form::Accordion:0x000000012f0b4ca0 @account=#<A...
```

or

```
Completed 500 Internal Server Error in 254ms (ActiveRecord: 49.0ms | Allocations: 68131)
  
ActionView::Template::Error (undefined method `<<' for nil:NilClass):
    10:   id="<%= dom_id(employee) %>" 
    11:   class="<%= show_employees_out employee %> relative flex items-center space-x-3 rounded-lg border <%= set_border_punch_clock employee %> <%= set_emp_bg_color_on_state employee.state %> px-6 py-3 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:border-gray-400">
    12:   <div class="flex-shrink-0">
    13:     <%= render_mugshot( employee, class: "h-8 w-8 rounded-full ring-4 ring-white sm:h-10 sm:w-10" )  %>
    14:   </div>
    15:   <div class="min-w-0 flex-1">
    16:     <div >
  
app/views/components/mugshot.rb:23:in `paint_mugshot'
```

**Comment by joeldrapper** [comment]
Looks like a few different errors here.

1. The method formerly called `text` has been renamed `plain` in order to support SVG’s `text` elements.
2. What's on line 23 of `mugshot.rb` (mentioned in the second error)?

**Comment by wdiechmann** [comment]
hurrying to fix the 'text' stuff - just wondering why Murphy got mixed up in this 😆 - I mean: what are the odds that any odd number of errors converge like all planets in the Solar System 🤭 

sorry to waste your bandwidth 😊

**Comment by joeldrapper** [comment]
Glad you got it sorted! 🙌

**Comment by wdiechmann** [comment]
well yeah - and then not at all... 🆘 

There must be something fundamentally different - all my components suddenly seem to be filled with litter 😭 

Like this 3rd line - why is this not _comme'il faut_ anymore?

```
#app/views/components/breadcrumbs.rb:23-31

            li do
              div do
                link_to( helpers.root_path, class: "text-gray-400 hover:text-gray-500") do
                  #  <!-- Heroicon name: solid/home -->
                  svg( class: "flex-shrink-0 h-5 w-5", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 20", fill: "currentColor", aria_hidden: "true") do |s|
                    s.path( d: "M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z")
                  end
                  span( class: "sr-only") {Dashboard}
                end

```


```
Completed 500 Internal Server Error in 223ms (ActiveRecord: 42.2ms | Allocations: 126891)


  
ActionView::Template::Error (undefined method `<<' for nil:NilClass):
    3:   data-controller="list-item-actions"
    4:   data-list-item-actions-list-outlet="#list"
    5:   class="max-w-full mx-auto sm:px-6 lg:px-8" >
    6:   <%= render_list_header( \
    7:     title: raw_t("#{resource_class}.index"), 
    8:     description: raw_t("#{resource_class}.index_description"), 
    9:     breadcrumbs: @breadcrumbs, 
  
app/views/components/breadcrumbs.rb:25:in `block (4 levels) in template'

```

**Comment by willcosgrove** [comment]
@wdiechmann it's difficult to know exactly what's wrong here. Maybe to rule some things out, try using an `a` instead of a `link_to` on line 25 and see what happens then? Also the span on line 30 looks unusual. Is `Dashboard` a constant defining a string? Or another component?

**Comment by wdiechmann** [comment]
I understand that - and it's not like I'm fishing for you guys to fix my sh*t 

I'm just very surprised to learn the amount of change to either Ruby (or Phlex 1.4 -> 1.9)

I think I did try it for size a ways back only to see the bulk of issues rising above me standing tall 😉 

Guess I'll save this battle for a rainy day and _crawl back under that stone from where I came_

thanks so much for all your hard work on Phlex - wouldn't miss it for the world 🎈

**Comment by joeldrapper** [comment]
There have been a lot of changes since `1.4`. I recommend reading through the release notes here, starting at `1.5`. https://github.com/phlex-ruby/phlex/releases

**Comment by wdiechmann** [comment]
Peek'a'boo - I'm back (and not with a vengeance - but with gratitude 💌 )

Fast forward to `gem 'phlex-rails', '1.1.1'` and all is quiet on the northern front you could say 🎉 

Once again allow me to extend my appreciation - I cannot stress the importance and quality of Phlex enough!

Now all we have left is - World domination! 
🤣 

ps: Phlex is so much 'lighter' in contrast to ViewComponent - @joelhawksley take note 😉

**Comment by willcosgrove** [comment]
Yay 🎉 I'm glad you're unblocked!

I'm also glad you're enjoying using Phlex!

It makes different trade offs than ViewComponent. Phlex jives more with how I like to think about views, but I've also talked to plenty of people who find ViewComponent to be easier to grasp conceptually. There's definitely room in the Ruby ecosystem for both! 🤗 

I probably never would have tried Phlex had I not first been convinced of the componentization of views by ViewComponent. @joelhawksley and team have done a great job on it!
