### ISSUE TITLE
Mix by default

### ISSUE THREAD

**Issue by willcosgrove** [phlex-ruby/phlex#627]
This may have too many performance implications, but while we're dreaming...

I use `mix` quite a bit to allow callers to decorate the final markup with maybe an additional class, or a stimulus data attribute. I wonder if we could use the heretofore unused positional argument(s) of the element methods to support mixing the attributes.

I find the code for using `mix` a bit ugly:

```rb
div(**mix({class: "default classes"}, customized_attributes))
```

If the performance was too big of a hit, I could also see just having a way to opt in to that behavior per element call still being cleaner looking.

Maybe something like

```rb
mixed.div(customized_attributes, class: "default classes")
```

**Comment by joeldrapper** [comment]
This could be an opted-in via a configuration on the class.

**Comment by joeldrapper** [comment]
I don’t think there’s enough motivation for this feature at this time. It could come up again like Kits did but for now I think it makes sense to close this issue.
