### ISSUE TITLE
Test for precedence of `to_s`, `to_str`, and `to_phlex_attribute_value`

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#638]
_Originally posted by @willcosgrove in https://github.com/phlex-ruby/phlex/pull/629#discussion_r1471306264_

**Comment by sullyvannunes** [comment]
I would like to work on this issue. 

However, I don't know exactly how to execute the tests in `gd` directory. It seems `sus` isn't the right tool to run them. Am i right?

**Comment by joeldrapper** [comment]
Yes, ignore the `gd` directory, we haven’t migrated there yet. `bundle exec sus` should run the `sus` test suite.
