### ISSUE TITLE
Unable to render svg element with a nested path.  

### ISSUE THREAD

**Issue by tubsandcans** [phlex-ruby/phlex#646]
The following should render an svg element with a nested <path>, but it's only rendering the svg, which produces no visible element. Phlex v1.9

~~~
              svg(
                class: "w-6 h-6 mr-2 text-gray-800 dark:text-white",
                aria_hidden: "true",
                xmlns: "http://www.w3.org/2000/svg",
                fill: "currentColor",
                viewbox: "0 0 24 24"
              ) do |s|
                s.path(
                  fill_rule: "evenodd",
                  d: "M5 5c.6 0 1-.4 1-1a1 1 0 1 1 2 0c0 .6.4 1 1 1h1c.6 0 1-.4 1-1a1 1 0 1 1 2 0c0 .6.4 1 1 1h1c.6 0 1-.4 1-1a1 1 0 1 1 2 0c0 .6.4 1 1 1a2 2 0 0 1 2 2v1c0 .6-.4 1-1 1H4a1 1 0 0 1-1-1V7c0-1.1.9-2 2-2ZM3 19v-7c0-.6.4-1 1-1h16c.6 0 1 .4 1 1v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Zm6-6c0-.6-.4-1-1-1a1 1 0 1 0 0 2c.6 0 1-.4 1-1Zm2 0a1 1 0 1 1 2 0c0 .6-.4 1-1 1a1 1 0 0 1-1-1Zm6 0c0-.6-.4-1-1-1a1 1 0 1 0 0 2c.6 0 1-.4 1-1ZM7 17a1 1 0 1 1 2 0c0 .6-.4 1-1 1a1 1 0 0 1-1-1Zm6 0c0-.6-.4-1-1-1a1 1 0 1 0 0 2c.6 0 1-.4 1-1Zm2 0a1 1 0 1 1 2 0c0 .6-.4 1-1 1a1 1 0 0 1-1-1Z",
                  clip_rule: "evenodd"
                )
              end
~~~

**Comment by joeldrapper** [comment]
Oh, I think I might know what the issue could be. If this is in a `Phlex::SVG` component, you don’t need to pick up `|s|` and call `path` on `s`. Instead, you can just call `path` on `self`.

If it's in a `Phlex::HTML` component, the `svg` method there yields an instance of a `Phlex::SVG`, which you can call methods on. This allows you to use SVG methods from an HTML context.

**Comment by tubsandcans** [comment]
I've tried it both ways, neither one of which produces any nested path element. I've also tried making an 'Icon' class and having that inherit from Phlex::SVG or Phlex::HTML and rendering that in my template, which weirdly produces nothing, not even an svg element.

**Comment by tubsandcans** [comment]
It looks like there was some issue with the plain content following the svg element. It was calling a method that was overridden by a stub generated by phlexing.fun. Thanks for the help on this!
