### ISSUE TITLE
Sort attributes and tokens for better compression

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#672]
We should probably sort attributes and known token lists for better compression. A repeated list of dozens of classes can be very efficiently compressed by Gzip, etc. if it is always listed in the same order.

**Comment by bradgessler** [comment]
There's a recommended order for Tailwind classes documented at https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted if we're talking about CSS token ordering.

**Comment by joeldrapper** [comment]
I think we should just use alphabetical ordering. It makes sense for prettier to order them like this in your source files, but for distribution, we can just use whatever is fastest. As long as the order is consistent, there should be some good consistent chunks for compression.

**Comment by bradgessler** [comment]
The gzippopotamus will be pleased 🦛🤐
