### ISSUE TITLE
Phlex components should act as Kits for nested components

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#686]
Let’s say we have some components like this

```ruby
class Components::Card < ApplicationComponent
  def view_template(&)
    article(class: "card", &)
  end
end

class Components::Card::Heading < ApplicationComponent
  def view_template(&)
    h1(class: "card-heading", &)
  end
end

class Components::Card::Body < ApplicationComponent
  def view_template(&)
    div(class: "card-body", &)
  end
end
```

We need to answer the following questions:

1. Should we be able to render `Components::Card::Body()` directly? I think yes.
2. Should we be able to render `Heading()` from `Components::Card`? Probably yes.
3. Should we be able to render `Body()` from `Components::Card::Heading`? I’m not sure about that.

**Comment by willcosgrove** [comment]
Is that a pattern we want to encourage? At least in this specific example, I think we would probably both say that this is better modeled as one view `Component::Card`, with methods defined on it for rendering the heading and body.

```rb
class Components::Card < ApplicationComponent
  def view_template(&)
    article(class: "card", &)
  end

  def heading(&) = h1(class: "card-heading", &)
  def body(&) = div(class: "card-body", &)
end
```

The smell test being: do I ever need to render `Components::Card::Body` outside of `Components::Card`? If you do, then maybe it's not a `Card::Body` maybe it's something else that a Card just happens to also use as its body.

Anytime I have defined a component under another component's namespace, the purpose was always to "hide" the component or strongly signal to the reader that this is just for the parent component to use. So exposing nested components as Kits would flip that on its head.

**Comment by joeldrapper** [comment]
Yeah, you’re right. If you wanted to make `CardBody` exposed, you could just put it in the Kit right next to `Card`.
