### ISSUE TITLE
Dropping support for Ruby < 3.2 in 2.0

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#687]
I’m considering whether we should drop support for Ruby versions below 3.2, since 3.2 is where the `Fiber[]` and `const_added` features we depend on for `Phlex::Kit` were introduced.

We could still maintain a Phlex 1.0 branch supporting Ruby >= 2.7 for a few more years. I just think it might be easier to say, “here’s the features in 2.0” without having to qualify which Ruby versions have access to them.

**Comment by dhnaranjo** [comment]
Ship it and solicit https://github.com/ruby-next/ruby-next implementations from anyone who finds themselves locked out and unable to upgrade Ruby.
