### ISSUE TITLE
Can't get initial example working, even on vanilla rails install - only last element renders

### ISSUE THREAD

**Issue by AlexMuir** [phlex-ruby/phlex#688]
The example at https://phlex.fun under "Why render HTML with Ruby?" only renders the final child.   

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]

I setup a blank app (tried on Rails 7.1.2 and 7.1.3.2)

```bash
rails -v 
# => Rails 7.1.3.2
rails new TestingPhlex
bundle add phlex-rails
rails g phlex:install
rails g controller posts index
```

```ruby
# app/views/components/nav.rb as per docs
class Nav < Phlex::HTML
  def template(&content)
  	nav(class: "main-nav") {
	  ul(&content)
  	}
  end

  def item(url, &content)
  	li { a(href: url, &content) }
  end
end
```

```erb
# app/views/posts/index.html.erb as per docs
<%= render Nav.new do |nav|
	nav.item("/") { "Home" }
	nav.item("/about") { "About" }
	nav.item("/contact") { "Contact" }
end %>
```

**Output received**
```html
<nav class="main-nav">
   <ul>
      <li><a href="/contact">Contact</a></li>
   </ul>
</nav>
```

**Expected** - as detailed in docs.
```html
<nav class="main-nav">
  <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About</a></li>
    <li><a href="/contact">Contact</a></li>
  </ul>
</nav>
```

**Comment by joeldrapper** [comment]
This code only works from another Phlex context, but you’re calling it from ERB.

```ruby
render Nav.new do |nav|
  nav.item("/") { "Home" }
  nav.item("/about") { "About" }
  nav.item("/contact") { "Contact" }
end
```

To use it in ERB, you would have to use ERB output tags, e.g.

```erb
<%= render Nav.new do |nav| %>
  <%= nav.item("/") { "Home" } %>
  <%= nav.item("/about") { "About" } %>
  <%= nav.item("/contact") { "Contact" } %>
<% end %>
```

**Comment by AlexMuir** [comment]
Well Joel - that's an outrageously fast reply.  Thank you!  It might be worth adding this to the docs although with hindsight it's completely obvious and doesn't seem to have tripped anyone else up!

**Comment by joeldrapper** [comment]
> Well Joel - that's an outrageously fast reply. Thank you!

We get notifications in the [Naming Things Discord](https://discord.gg/vdHATT5Pws) so I saw this straight away 😅

Totally agree about the docs. We’re preparing to release 2.0, which will have completely new docs and hopefully make this kind of thing much clearer. 🙏

**Comment by AlexMuir** [comment]
Brilliant, I'm a convert!  It's not immediately obvious from the Github that clicking the logo takes you to the docs.  Maybe you could add a 'Read the docs' text link below.  

Thanks for your work on this!  There's a beauty to it: I think it gets the closest yet in Ruby to the niceties of building UI in, eg. React. 

```jsx 
// Based on Radix UI
<Dropdown.Root>
  <Dropdown.Trigger>Click me!</Dropdown.Trigger>
  <Dropdown.Content>
     <Dropdown.Item>An option</Dropdown.Item>
     <Dropdown.Item>Another options</Dropdown.Item>
     <Dropdown.Separator />
     <Dropdown.Item>And finally...</Dropdown.Item>
  </Dropdown.Content>
</Dropdown.Root>
```

Rails Helpers are a dead end for the obvious reasons.   

Trying to replicate this with ViewComponents just doesn't feel natural to me: the concept of Slots isn't right to represent multiple different types of content. 

To represent the same (using Github's Primer as an example): 

```ruby
render(Primer::Alpha::ActionMenu.new(select_variant: select_variant, anchor_align: anchor_align, anchor_side: anchor_side, size: size)) do |menu|
  menu.with_show_button { "Menu" }
  menu.with_item(label: "Copy link")
  menu.with_item(label: "Quote reply")
  menu.with_item(label: "Reference in new issue")
  menu.with_divider
  menu.with_item(label: "Edit")
  menu.with_item(label: "Delete", scheme: :danger)
end
```


```ruby
<%# An effort with Phlex %>
<%= render UI::Dropdown.new do |dd| %>
  <%= dd.item { 'An item' } %>
  <%= dd.item { 'Another item' } %>
  <%= dd.separator %>
  <%= dd.item do %>
    And finally...
  <% end %>
<% end %> 
```

Much better!  In my mind, ActionHelper is methods (one or two liners). Phlex is builders (classes, generators, components, whatever people want to call them).  

Just a brain dump!  No reply needed!

**Comment by joeldrapper** [comment]
> Brilliant, I'm a convert! It's not immediately obvious from the Github that clicking the logo takes you to the docs. Maybe you could add a 'Read the docs' text link below.

👍 Agreed

> I think it gets the closest yet in Ruby to the niceties of building UI in, eg. React.

You should see what’s coming in 1.10 with the new Kit feature! (previously called Buckets). There’s an example in this PR. https://github.com/phlex-ruby/phlex/pull/676
