### ISSUE TITLE
Make __vanish__ part of the public API

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#698]
### Discussed in https://github.com/orgs/phlex-ruby/discussions/583

<div type='discussions-op-text'>

<sup>Originally posted by **bradgessler** July 21, 2023</sup>
Sometimes a component needs to be rendered, but the output is not needed, like in this controller at https://github.com/rubymonolith/classic/blob/47d9fee6e17f5f49d7dfbefee4b194b6eddcff8d/app/controllers/posts_controller.rb#L71-L73 so Superform can permit params based on the contents of a form.

Could this [`__vanish__` API](https://github.com//phlex-ruby/phlex/blob/9e5820dc69cb243e31b924f00390deb45be18fb3/lib/phlex/sgml.rb#L238-L248) be made available for such calls? I see I can include `DeferredRender` to enable that, but I only need this for permitting params. When I'm actually rendering the form in a view I don't need to defer rendering.</div>

**Comment by Vagab** [comment]
@joeldrapper I'm willing to do this, I was wondering how do you imagine that would look?
My thinking is something like this:
```ruby
  render ComponentToVanish.new(...).vanish
```

**Comment by joeldrapper** [comment]
I think it would mainly be used from inside the `view_template` method.

```ruby
def view_template
  vanish do
    render SomeComponent.new
  end
end
```

Essentially all we need to do is rename the method removing the underscores.

**Comment by Vagab** [comment]
> I think it would mainly be used from inside the view_template method.

might be misunderstanding the use case, but if it's used in the `view_template`, then what's the difference with just including `DeferredRender`? From @bradgessler's example it seems that it should be a regular template that just get's vanished when called from a specific context. Or am I missing something?

**Comment by bradgessler** [comment]
Yeah, ideally I can vanish a component without having to throw it inside of another component.

If I were to implement Superform strictly to this spec, I'd have a VanishComponent that I'd pass the form component into, which would be kind of weird.

**Comment by Vagab** [comment]
@joeldrapper do you think it's worth doing something like what I suggested initially?

**Comment by Vagab** [comment]
@joeldrapper boop

**Comment by joeldrapper** [comment]
I think it would be reasonable for vanish to take either:

a _renderable_ as the first positional argument, e.g.
```ruby
vanish MyComponent.new
```

or a block, e.g.
```ruby
vanish do
  h1 { "vanish this" }
end
```

**Comment by bradgessler** [comment]
If the positional argument works from a controller, that would cover my use case of needing to vanish a form in Superform.

If it's only a block, I'd have to do some gymnastics with a throw-away n the controller to make it work.

**Comment by joeldrapper** [comment]
Neither would work form a controller. The only time Phlex supplements controllers is when you include `Phlex::Rails::Streaming`.

**Comment by Vagab** [comment]
@joeldrapper @bradgessler correct me if I'm wrong, but I don't think the suggestion of calling `vanish` from inside the component covers the initial use case this issue was created with. Should we consider having the ability to vanish from a controller? Maybe:
```ruby
render Component.new(...).vanish
# or
render Component.vanish(...)
# or
include Phlex::Vanish
vanish Component.new(...)
```

otherwise if the direction you wanna go is vanishing from inside the controller then I can just make `__vanish__` public and rename it. Lmk wyt

**Comment by thedumbtechguy** [comment]
> @joeldrapper I'm willing to do this, I was wondering how do you imagine that would look? I was thinking about something like this:
> 
> ```ruby
>   render ComponentToVanish.new(...).vanish
> ```

I have a component forked off of Superform as well that needs this.

Current `__vanish__` looks like it works as @joeldrapper describes here https://github.com/phlex-ruby/phlex/issues/698#issuecomment-2282193904.

However, the way you described it is how I actually need to use it.

I have a `form` which I wish to call `vanish` on. 
This can happen anywhere, so I don't want `vanish form`, I want `form.vanish`.

**Comment by thedumbtechguy** [comment]
My actual implementation is a workaround that invokes [#call](https://github.com/radioactive-labs/phlexi-form/blob/main/lib/phlexi/form/base.rb#L81)

**Comment by bradgessler** [comment]
That checks out with how I use it in my implementations.

One thought: when the form is actually invalid, the output that was rendered should actually be displayed. Vanishing it means it would have to be rendered again without vanishing.

I think what I'd actually want is a way to render the view; if the form is valid I'd end up throwing that view away and redirecting the user to the success page. When the form is invalid, I'd actually want to render the output of Superform to the user since it would already have the UI rendered with error messages, etc.

**Comment by joeldrapper** [comment]
From what I’m hearing, it seems like you really need lower-level hooks into Phlex’ renderable interface so you can have custom form objects that are renderable in specific ways. I think ideally, those wouldn't inherit from Phlex::HTML and then use vanish to undo part of Phlex::HTML’s behaviour.
