### ISSUE TITLE
Escape hatch to bypass Phlex HTML safety

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#718]
@bradgessler recently brought up the need for this again, and suggested having a `safe` method that we can use to wrap any safe value.

```ruby
div(onclick: safe("foo")) { "Foo" }
a(href: safe("javascript:bar")) { "Bar" }
```

I think this would work quite nicely. `safe` could return a `Phlex::SafeValue`, e.g.

```ruby
def safe(value)
  Phlex::SafeValue.new(value)
end
```

And we can check for that when building attributes.

```ruby
if Phlex::SafeValue === value
  ...
end
```

**Comment by bradgessler** [comment]
Draft PR at https://github.com/phlex-ruby/phlex/pull/719

**Comment by joelmoss** [comment]
What's the difference between `unsafe_raw` and this?

**Comment by joeldrapper** [comment]
You can't use unsafe raw around an attribute, you would need to write the whole element by hand.
