### ISSUE TITLE
Method to make binding the `class` kwarg easier

### ISSUE THREAD

**Issue by bradgessler** [phlex-ruby/phlex#720]
Its common to want to intercept the `class` kwarg like this:

```ruby
  def input(*, class: "hi", **, &)
    super(*, class: tokens(keyword(class:)))
  end
```

Phlex could have a method that makes this possible like this:

```ruby
    def keyword(**bindings)
      if bindings.size > 1
        bindings.values
      else
        bindings.values.first
      end
    end
```

Not sure if `keyword` is the right method name. Some possible method names are:

```
bind
keyword
keywords
value
values
grab
```

Previous attempt at https://github.com/phlex-ruby/phlex/pull/717 broke the way `tokens` behaved and was less composable. I believe this approach solves both of those problems.

**Comment by joeldrapper** [comment]
I quite like this with the name `grab`. @willcosgrove what are your thoughts?

**Comment by willcosgrove** [comment]
I like `grab` too. It is solving an interesting problem. I'm kind of surprised I haven't run into a need for it yet 🤔

In the example given, I would just use `mix` and not have any need to grab out the class kwarg.

**Comment by joeldrapper** [comment]
Oh, of course you can already use `mix` for this. I’m trying to be very careful about what features we introduce in core, but I don’t think this represents a significant increase in complexity or maintenance burden. It’s the kind of thing that’s useful if you need it and disappears if you don’t, which I like.

**Comment by joeldrapper** [comment]
Even though you can technically use `mix`, with `**mix(:class)`, I think something like this is quite a bit simpler when all you’re doing is passing along the `class`.

```ruby
def foo(class:)
  div(class: [grab(:class), "some other classes here"])
end
```
