### ISSUE TITLE
Weird autoloading bug

### ISSUE THREAD

**Issue by Vagab** [phlex-ruby/phlex#727]
Prerequisites:
we have a `app/views/components` directory which is added to the autoloaded paths during initialization of the app, i.e.:
```ruby
Rails.autoloaders.main.tap do |loader|
  loader.push_dir(Rails.root.join("app", "views").to_s)
end
```
there's also a `app/views/components.rb` which is just:
```ruby
module Components
  extend Phlex::Kit
end
```
now if we do something like this:
```ruby
# app/views/components/a.rb
class Components::A < Phlex::HTML
  def self.a
    # whatever
  end
end

# app/views/components/b.rb
class Components::B < Components::A
  a
end
```
we get an error saying `a is undefined`. Funnily enough I think it's order dependent if we switch `A` and `B`, i.e. make `B` inherit from `A`, everything works fine. I'm not sure why that happens and maybe there's something wrong on our side, but [here's](https://github.com/Vagab/phlex-wat) a minimal reproduction. It's a fresh `rails new` with the described above changes.
> Note: Oh, I've also added `eager_load = true` to the development just so you can see it crash as soon as you `rails c`. Without `eager_load` it will crash when irb loads it which is usually when you type `Components` into it.

**Comment by joeldrapper** [comment]
Hey @Vagab, I can’t reproduce this. Can you send me the full stack trace for the error you hit? Also, which version of Rails are you using? Are you using Zeitwerk?

Alternatively, if you can get a reproduction in a fresh rails app somewhere, that would be really helpful.

**Comment by joeldrapper** [comment]
Could you try configuring the autoloader with this in `application.rb`?

```ruby
config.autoload_paths << "#{root}/app/views"
```

**Comment by Vagab** [comment]
> Alternatively, if you can get a reproduction in a fresh rails app somewhere, that would be really helpful.

the original post contains a link to on

I will try the suggested autoloader fix, thank you!

**Comment by joeldrapper** [comment]
I missed the link. Thanks!

**Comment by Vagab** [comment]
@joeldrapper I'm not 100% sure but I think [this](https://github.com/phlex-ruby/phlex/pull/728) might be the fix

**Comment by Vagab** [comment]
@joeldrapper might be a stupid question, but maybe one of the reasons this happens. I noticed the `Kit` containing `def included(mod)`, but I always thought it's `def self.included(mod)`. I've made a [pr](https://github.com/phlex-ruby/phlex/pull/728) that  changed that, but at the same time I broke some tests 😅

**Comment by joeldrapper** [comment]
Yeah, that’s not quite it, but I bet that’s close to where the bug is. 🤔

**Comment by joeldrapper** [comment]
I expect it’s because we iterate over each constant and load them at that point, without doing anything to ensure there aren’t dependencies between them that are required at load time, e.g. calling out to abstract class methods.

**Comment by Vagab** [comment]
yeah something like that. I don't know how the actual loading works tbh, but it seems that the bug stems from the difference between getting the const and actually loading all of the class contents

**Comment by Vagab** [comment]
to be more precise, I can see the difference with the regular eager loading and loading when the `constants.each { |c| const_get(c) if autoload?(c) } is also ran, and the former is:
```
load A
read A
load B
read B
```
the latter is
```
load A
load B
read B
# obviously error
```

**Comment by joeldrapper** [comment]
I managed to check out the reproduction. Thank you. It's clearly coming from Phlex and I think it's because components include all other components in their namespace. I'll see if I can fix it.

**Comment by joeldrapper** [comment]
I think I have a fix. Need to test it further and make sure nothing else is broken. https://github.com/phlex-ruby/phlex/pull/729
