### ISSUE TITLE
Nested kits

### ISSUE THREAD

**Issue by Vagab** [phlex-ruby/phlex#731]
I was wondering, does it make sense to make nested modules(I don't think it's possible if the namespace is a class but 🤷‍♂️ ) automatically extend `Phlex::Kit`?
So that it's possible to do this:
```ruby
module Components
  extend Phlex::Kit
end

class Components::A::B
  def view_template
    # ...
  end
end

# and then somewhere
Components::A::B()
```

Afaiu currently one has to:
```ruby
module Components::A
  extend Phlex::Kit
end
```

**Comment by cirdes** [comment]
@joeldrapper, I was looking for something similar. Let's take PhlexUI, for example.

Here is the current Accordion syntax:

```
render PhlexUI::Accordion.new do
  render PhlexUI::Accordion::Item.new do
    render PhlexUI::Accordion::Trigger.new do
      div do
        p{ "What is PhlexUI?" }
      end
    end
      
    render PhlexUI::Accordion::Content.new do
      p { "PhlexUI is a UI component library for Ruby devs who want to build better, faster." }
    end
  end
end
```

I was planning to open a PR so it could become:

```
PhlexUI::Accordion do
  PhlexUI::Accordion::Item do
    PhlexUI::Accordion::Trigger do
      div do
        p { "What is PhlexUI?" }
      end
    end
  
    PhlexUI::Accordion::Content do
      p { "PhlexUI is a UI component library for Ruby devs who want to build better, faster." }
    end
  end
end
```

PhlexUI is based on internal modules being exposed to be composable as blocks.

I know that PhlexUI has a builder, but I don't like it. PhlexUI was inspired by ShadCN in the React world, and the [accordion](https://ui.shadcn.com/docs/components/accordion) there looks something like this:

```
Accordion type="single" collapsible className="w-full">
  <AccordionItem value="item-1">
    <AccordionTrigger>Is it accessible?</AccordionTrigger>
    <AccordionContent>
      Yes. It adheres to the WAI-ARIA design pattern.
    </AccordionContent>
  </AccordionItem>
</Accordion>
```

One thing is if Phlex doesn't encourage exposing internal parts, but if you decide not to support it, it will be disappointing. =/

**Comment by joeldrapper** [comment]
I would refactor `PhlexUI` to be like this.

```ruby
PhlexUI::Accordion do |accordion|
  accordion.item do
    accordion.trigger do
      div do
        p { "What is PhlexUI?" }
      end
    end
  
    accordion.content do
      p { "PhlexUI is a UI component library for Ruby devs who want to build better, faster." }
    end
  end
end
```

Alternatively, if `AccordionContent` is a global thing, you could expose `PhlexUI::AccordionContent` directly in the `PhlexUI` namespace.

**Comment by cirdes** [comment]
@joeldrapper , you are right PhlexUI::AccordionContent could be a global thing and become

```ruby
PhlexUI::Accordion do
  PhlexUI::AccordionItem do
    PhlexUI::AccordionTrigger do
      div do
        p { "What is PhlexUI?" }
      end
    end
  
    PhlexUI::AccordionContent do
      p { "PhlexUI is a UI component library for Ruby devs who want to build better, faster." }
    end
  end
end
```
or like you suggest before.

**Comment by Vagab** [comment]
@joeldrapper but then one would probably prefer to use `PhlexUI::Accordion::Item` inside `PhlexUI::Accordion`. And it would be nice if that was just `Item()` there. But I guess it's still possible if we're explicitly extending the module so it should be fine

**Comment by joeldrapper** [comment]
You could use capital letters for methods on the accordion. Could even use `::` instead of `.`

```ruby
PhlexUI::Accordion do |accordion|
  accordion::Item do
    accordion::Trigger do
      div do
        p { "What is PhlexUI?" }
      end
    end
  
    accordion::Content do
      p { "PhlexUI is a UI component library for Ruby devs who want to build better, faster." }
    end
  end
end
```

**Comment by Vagab** [comment]
what I meant is that inside the `Accordion`s `view_template`, or inside a slot. But what I'm understanding from [this](https://github.com/phlex-ruby/phlex/issues/732) issue is that supporting extending a class is not something you aim to do so I think manually extending a module should work well enough. Thank you

**Comment by joeldrapper** [comment]
You can do that if you define the methods yourself.

```ruby
class Accordion < Phlex::HTML
  def view_template
    # ...
  end

  def Item(...)
    render Item.new(...)
  end
end

**Comment by Vagab** [comment]
yeah for sure, I got that. My sentiment is that it would be cool to still be able to avoid `render Item.new()` everywhere, even inside `Accordion`. I guess that's a purist in me talking 🙂

**Comment by iseth** [comment]
Since we can't do
```js

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
```

It would be nice to be able to include use certain components that only belong to the parent namespace and possibly another grandparent component to allow for more fine tuning of the main component.

@cirdes i agree there is a good use case for this.

**Comment by joeldrapper** [comment]
I wonder if you could achieve the same result with delegate.
```ruby
delegate :Card, to: PhlexUI
```

**Comment by cirdes** [comment]
@joeldrapper, I'm trying to test this concept here:

```ruby
# frozen_string_literal: true

module Lui
  extend Phlex::Kit

  autoload :Accordion, "lui/accordion"
  # autoload :AccordionContent, "lui/accordion/content"
end
```

When `AccordionContent` is removed, the `Accordion` is loaded correctly. However, if I add `AccordionContent`, I get the following error:

```bash
irb(main):001> Lui::Accordion
app/views/components/lui/accordion/content.rb:4:in `<module:Lui>': uninitialized constant Lui::Accordion (NameError)

  class Accordion::Content < Base
        ^^^^^^^^^
Did you mean?  Lui::AccordionContent
```

Maybe this [https://github.com/phlex-ruby/phlex/pull/729](https://github.com/phlex-ruby/phlex/pull/729) has solved it, but I can't make it run directly from GitHub either:

```ruby
gem "phlex-rails", "1.2.1"
gem "phlex", git: 'https://github.com/phlex-ruby/phlex'
```

```bash
Resolving dependencies.....
Bundler could not find compatible versions for gem "phlex":
  In Gemfile:
    phlex

    phlex-rails (= 1.2.1) was resolved to 1.2.1, which depends on
      phlex (~> 1.10.0)
```
Is it possible to release a new phlex version with the fix?

**Comment by Vagab** [comment]
@cirdes I think if you(untested):
```ruby
gem "phlex", "~> 1.10",  git: "https://github.com/phlex-ruby/phlex", branch: "1.10"
```
it should work

**Comment by cirdes** [comment]
thanks, @Vagab !

**Comment by cirdes** [comment]
I'm getting closer:

app/views/components/lui.rb
```ruby
module Lui
  extend Phlex::Kit

  autoload :Accordion, "lui/accordion"
  autoload :AccordionContent, "lui/accordion/content"
end
```
app/views/components/lui/accordion.rb
```ruby
module Lui
  class Accordion < Base

    def view_template(&)
      div(**attrs, &)
    end

    private

    def default_attrs
      { class: "w-full" }
    end
  end
end
```

app/views/components/lui/accordion/content.rb
```ruby
# frozen_string_literal: true

module Lui
  class Accordion::Content < Base
    def view_template(&)
      div(**attrs, &)
    end

    private

    def default_attrs
      { data: { accordion_target: "content" }, class: "overflow-y-hidden", style: "height: 0px;" }
    end
  end
end
```

This code renders without problem
```ruby
module Phlexs
  class ShowView < ApplicationView
    def view_template
      h1 { "Phlexs::Show" }

      Lui.Accordion { h2 { "AccordionContent" } }
    end
  end
end
```

But that one I got errors:
```ruby
# frozen_string_literal: true

module Phlexs
  class ShowView < ApplicationView
    def view_template
      h1 { "Phlexs::Show" }

      # Lui.Accordion { h2 { "AccordionContent" } }
      Lui.Accordion { Lui.AccordionContent { h2 { "AccordionContent" } } }
    end
  end
end
```
<img width="757" alt="Screenshot 2024-06-22 at 12 39 50 PM" src="https://github.com/phlex-ruby/phlex/assets/727781/b61cc32d-a7c1-4ee9-a8c2-8a40eb017845">

**Comment by Vagab** [comment]
@cirdes in this specific case you've missed `::` between `Accordion` and `Content`
