### ISSUE TITLE
Class `Phlex::Kit`

### ISSUE THREAD

**Issue by Vagab** [phlex-ruby/phlex#732]
Another thing which I think is related to [this](https://github.com/phlex-ruby/phlex/issues/731#issuecomment-2163611141) comment is whether it can be made possible to extend classes with `Phlex::Kit`? I imagine the only thing standing in the way is [this](https://github.com/phlex-ruby/phlex/blob/e4aecac723a5352b2bfb2b3ed4f7274fa13370cb/lib/phlex/kit.rb#L50), but I'm not 100% sure.

**Comment by joeldrapper** [comment]
The problem is part of the contract with kits is that you can include them. For example, I have this in one of the apps I work on.

```ruby
class ApplicationView < Phlex::HTML
  include Components

  # ...
end
```

**Comment by Vagab** [comment]
yeah that makes sense. Thanks!
