### ISSUE TITLE
Inline tags declaration

### ISSUE THREAD

**Issue by Xanderwot** [phlex-ruby/phlex#750]
Hi everyone,

I have a question (more like an advice) about phlex tag registration improvement.

We are doing a migration from another rendering gem ([fortitude](https://github.com/ageweke/fortitude)) to phlex and have a lot of legacy code, which supports both block and inline tags:
```ruby
div do
  'Some content'
end

# returns same result
div 'Some content'
```

I did patch `register_element` method [here](https://github.com/phlex-ruby/phlex/blob/1.11.0/lib/phlex/elements.rb#L31) like this:
```ruby
def #{method_name}(inline_content = nil, **attributes, &block)
#...
          elsif inline_content.present? # with inline content
            buffer << "<#{tag}" << (Phlex::ATTRIBUTE_CACHE[respond_to?(:process_attributes) ? (attributes.hash + self.class.hash) : attributes.hash] || __attributes__(**attributes)) << ">"
            inline_content_block = Proc.new { inline_content }
            yield_content(&inline_content_block)
            buffer << "</#{tag}>"
          else
#...
end
```
(without attributes part also updated)

 to support both approaches and its works pretty good in most of places except some specific cases.

After applying this patch to a Phlex::HTML::StandardElements
```ruby
Phlex::HTML::StandardElements.module_eval { extend PhlexElementRegisterer }
```

and re-registering all elements with patched register_element method:
```ruby
Phlex::HTML::StandardElements.registered_elements.each do |method_name, tag|
  Phlex::HTML::StandardElements.register_element(method_name, tag: tag)
end
```

For example nested tags like tables:
```ruby
table do 
  tr do 
    td 'Content'
  end
end
```

generate expected html:
```html
<table>
  <tr>
    <td>Content</td>
  </tr>
</table>
```

but if I do something more specific:
```ruby
table do 
  tr do 
    td div { 'Content' }
  end
end
```

it moves div block outside table tag:
```html
<div>Content</div>
<table>
  <tr>
    <td></td>
  </tr>
</table>
```

When debugging I see that the div tag method was called with &block and after it the td method also called, but without any arguments or even a block.

As a second example it happens not only with table tag:
```ruby
def link_tag(text)
  div do
    link_to(text, '#')
  end
end

div class: 'first_nested' do
  div class: 'second_nested' do
    div link_tag('something'), class: 'third_nested'
  end
end
```

Will return:
```html
<div class="first_nested">
  <div class="second_nested">
    <div><a href="#">something</a></div>
    <div class="third_nested"></div>
  </div>
</div>
```

Maybe you will see how this issue can be solved? If solved, will this approach (supporting inline tags) be acceptable, as a future patch, to phlex (after it will be stable and test covered)?

Thanks!

**Comment by joeldrapper** [comment]
Patching this method is very likely to cause issues with Phlex upgrades. I wonder if we shouldn't just make Phlex support the first positional argument as text content by default. We originally wanted to stick to blocks for consistency with components, but I don’t see why we couldn't support both ways.

**Comment by Xanderwot** [comment]
I totally understand what I need to take care of my patch each time when upgrading phlex. I did modify it due 1.11.0 version now.

Anyway pls let me know if you have any ideas about improvements for my approach. I can open PR also if it will be easier to move forward with it.

Thanks

**Comment by joeldrapper** [comment]
Added in #755
