### ISSUE TITLE
Allow other types of content via element inline content

### ISSUE THREAD

**Issue by willcosgrove** [phlex-ruby/phlex#758]
Following up on #750 I think we should support all the same argument types as `plain`, so that would be adding: Integer, Float, Symbol, nil.

Allowing `nil` will require inverting the `Phlex::Null` concept: instead of using it as the default value for the inline content, we leave nil as the default value, and return `Phlex::Null` instead of `nil` from element methods. It probably needs a rename at that point to something more along the lines of `Phlex::ElementReturn`.

It could potentially be breaking because it's changing the return value of all the element calls, but I would be a little surprised if anyone is relying on elements always returning `nil`.

**Comment by Vagab** [comment]
@joeldrapper @willcosgrove I can handle this. Should I make a pr?

**Comment by joeldrapper** [comment]
@Vagab let’s wait on this discussion before we go any further. https://github.com/orgs/phlex-ruby/discussions/761
