### ISSUE TITLE
Make `__attributes__` public

### ISSUE THREAD

**Issue by joelmoss** [phlex-ruby/phlex#768]
Re: https://github.com/phlex-ruby/phlex/pull/766#issuecomment-2332546961

Now that `process_attributes` is gone, and the attributes cache is global, there is now a greater need to override/patch the `__attributes__` method. So I think it should be public.

**Comment by joeldrapper** [comment]
Caveats to patching this method are:

1. your patch must be deterministic because this is cached;
2. your patch must return the result of calling `super` otherwise you do not have HTML safety; and
3. any changes you make here could break third-party libraries that use Phlex.

**Comment by joeldrapper** [comment]
Making `__attributes__` public would introduce extra maintenance, support and documentation costs. My feeling is we shouldn’t do this unless there’s significant demand for it from a number of different users.

That said, @joelmoss, I don’t expect you will run into any issues patching the private method. You’re so actively involved in the project, you’d know if changes were upcoming.

@willcosgrove feel free to re-open this issue if you disagree and we can discuss further.
