### ISSUE TITLE
Chopping block

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#784]
Items in consideration for 2.0 chopping block:

### underscored method names
These could be replaced with `tag(:name)` though that feature will need re-implementing.

### yield_content
I think we can make `yield_content` private.

### view_context
We’ve already discussed renaming this `context`. We should really come up with a better name for Phlex internal context before we move forward with this.

### CSV helpers proxy
I think we should remove the helpers proxy for CSVs and instead allow `register_value_helper` in CSVs in Phlex-Rails.

### element clobbering guard
Without underscored methods, we wouldn’t need the clobbering guard.

### deferred render as a module
Instead of using a module for deferred render, I think it would be better to do something like

```ruby
def deferred = true
```

**Comment by hangsu** [comment]
None of these changes would pose a big roadblock for Clearscope's codebase.

**Comment by joeldrapper** [comment]
> None of these changes would pose a big roadblock for Clearscope's codebase.

Good to hear. Just trying to take advantage of the major release to get rid of a few things that have proven to be low-value.

**Comment by hangsu** [comment]
Maybe this isn't the right place for it, but we're in the process of upgrading to 2.0 beta and our only complaint is the forced dasherizing of symbol values in `__attributes__`. Dasherizing of keys has always been fine.

I wish it was at least easily overridden.

**Comment by hangsu** [comment]
Could there be a `format_attribute_value` method similar to `format_object` that can be overridden?

**Comment by joeldrapper** [comment]
@hangsu I opened this discussion to talk about that. We already had a 3-day debate about it in Discord 😆  https://github.com/orgs/phlex-ruby/discussions/785
