### ISSUE TITLE
Rendering boolean attributes

### ISSUE THREAD

**Issue by davidmilo** [phlex-ruby/phlex#801]
I am struggling to generate (alpinejs) attributes

```html
<body x-cloak x-data="{ mobileSidebarOpen: false }">
```

I tried different approaches (based on the documentation) but `x-cloak` is just ignored in my output
```ruby
# cody
body(x_cloak: true, x_data: "{ mobileSidebarOpen: false }")
body("x-cloak" => true, x_data: "{ mobileSidebarOpen: false }")
body(x: { cloak: true }, x_data: "{ mobileSidebarOpen: false }")

# result
<body x-data="{ mobileSidebarOpen: false }">
```

What am I doing wrong?

I am using
phlex (1.10.3)
phlex-rails (1.2.1)

**Comment by joeldrapper** [comment]
Can you post the HTML output that you would like?

**Comment by davidmilo** [comment]
The first snippet is what I want:

```html
<body x-cloak x-data="{ mobileSidebarOpen: false }">
```

**Comment by joeldrapper** [comment]
Any of these should work.

```ruby
body(x: { cloak: true, data: "{ mobileSidebarOpen: false }")
body(x_cloak: true, x_data: "{ mobileSidebarOpen: false }")
body("x-cloak" => true, "x-data" => "{ mobileSidebarOpen: false }")
```

**Comment by davidmilo** [comment]
They don't

I just tried to change `x` to something else for fun and it works. Could it be that `x` is somehow used/reserved for something else?

```
div(b_cloak: true) => <div b-cloak>
div(x_cloak: true) => <div>
```

Oh I just realized why: it is related to what AlpineJS does with x-cloak. They remove it once AlpineJS gets instantiated.

So sorry for wasting your time. 

Love Phlex ❤
